"""
Even Fibonacci Numbers
Problem 2

Each new term in the Fibonacci sequence is generated by
adding the previous two terms. By starting with 1
and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence
whose values do not exceed four million, find the sum
of the even-valued terms.

"""
import time

SOLUTION = 4613732


def test_solution() -> (bool, int):
    start_time = time.time()
    pass_ = main() == SOLUTION
    time_delta = time.time() - start_time
    return pass_, time_delta


def main():
    e = 1
    p = 1
    sum_even = 0
    while e < 4000001:
        e_hold = e
        e = p + e
        p = e_hold
        if e % 2 == 0:
            sum_even += e
    return sum_even
