"""
Even Fibonacci Numbers
Problem 2

Each new term in the Fibonacci sequence is generated by
adding the previous two terms. By starting with 1
and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence
whose values do not exceed four million, find the sum
of the even-valued terms.

"""

SOLUTION = 4613732


def test_correctness():
    assert count_fibonacci() == SOLUTION


def count_fibonacci():
    e = 1
    p = 1
    sum_even = 0
    while e < 4000001:
        e_hold = e
        e = p + e
        p = e_hold
        if e % 2 == 0:
            sum_even += e
    return sum_even


if __name__ == "__main__":
    from colorama import Fore

    if count_fibonacci() == SOLUTION:
        color = Fore.GREEN
    else:
        color = Fore.RED
    print(color + f"Solution for p002()={count_fibonacci()}")
