"""
Highly divisible triangular number
Problem 12
The sequence of triangle numbers is generated by adding the natural numbers.
 So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
 The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""
import time

SOLUTION = 76576500


def main():
    n = 4
    tri_num = 6
    while True:
        factors = FindFactors(tri_num)
        if len(factors) > 500:
            return tri_num
        tri_num = tri_num + n
        n = n + 1


def FindFactors(number):
    i = 1
    factors = set()
    while i not in factors:
        if number % i == 0:
            factors.add(i)
            factors.add(int(number / i))
        i = i + 1
    return factors


def test_solution() -> (bool, int):
    start_time = time.time()
    pass_ = main() == SOLUTION
    time_delta = time.time() - start_time
    return pass_, time_delta
